<?php
$configs = [
'services'=>['Prestazioni disponibili','Gestisci il listino dello studio','Nuova prestazione',['Descrizione','Durata','Costo'],[['Fisioterapia manuale','45 min','€ 55,00'],['Tecarterapia','45 min','€ 65,00'],['Massoterapia','30 min','€ 45,00'],['Rieducazione posturale','60 min','€ 70,00']]],
'invoices'=>['Fatture recenti','Documenti emessi e stato di pagamento','Nuova fattura',['Documento','Paziente','Data','Totale','Stato'],[['FT-2026/0089','Giulia Conti','03/09/2026','€ 120,00','Da pagare'],['FT-2026/0088','Elena Bianchi','02/09/2026','€ 65,00','Pagata'],['FT-2026/0087','Luca Romano','28/08/2026','€ 110,00','Pagata']]],
'payments'=>['Situazione pagamenti','Incassi registrati e importi sospesi','Registra pagamento',['Paziente','Fattura','Totale','Incassato','Residuo'],[['Giulia Conti','FT-2026/0089','€ 120,00','€ 0,00','€ 120,00'],['Sara Ferri','FT-2026/0082','€ 130,00','€ 65,00','€ 65,00'],['Paolo Villa','FT-2026/0078','€ 80,00','€ 40,00','€ 40,00']]],
'ledger'=>['Movimenti di prima nota','Entrate e uscite di tutti i conti','Nuovo movimento',['Descrizione','Importo','Data di pagamento','Conto di saldo'],[['Pagamento FT-2026/0088','+ € 65,00','02/09/2026','POS'],['Pagamento FT-2026/0087','+ € 110,00','28/08/2026','Bonifico'],['Materiale sanitario','− € 86,40','27/08/2026','Contanti']]],
'users'=>['Utenti di sistema','Persone abilitate ad accedere a Blueprint','Nuovo utente',['Utente','Email','Telefono','Ruolo'],[['Marco Rossi','marco@blueprint.it','333 551 8290','Amministratore'],['Anna Verdi','anna@blueprint.it','340 882 1190','Segreteria'],['Paolo Neri','paolo@blueprint.it','328 223 5571','Fisioterapista']]],
];
if($page==='statistics'): ?>
<section class="metrics"><article><div><span>FATTURATO 2026</span><strong>€ 72.840</strong><small class="up">↗ 8,6% anno su anno</small></div></article><article><div><span>PRESTAZIONI</span><strong>1.284</strong><small>Media 7,4 al giorno</small></div></article><article><div><span>TASSO NO-SHOW</span><strong>3,2%</strong><small class="up">↓ 0,8% rispetto al mese scorso</small></div></article></section><article class="panel chart-placeholder"><div class="panel-head"><div><h3>Andamento degli incassi</h3><p>Ultimi 6 mesi</p></div></div><div class="bars"><?php foreach([55,68,62,82,74,92] as $i=>$h):?><div><span style="height:<?=$h?>%"></span><small><?=['Apr','Mag','Giu','Lug','Ago','Set'][$i]?></small></div><?php endforeach?></div></article>
<?php elseif($page==='settings'): ?>
<div class="settings-grid"><article class="panel setting"><h3>Orari dello studio</h3><p>Configura giorni e fasce di apertura.</p><?php foreach(['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'] as $i=>$d):?><div><label><input type="checkbox" <?=$i<6?'checked':''?>> <?=$d?></label><span><?=$i<6?'08:00 — 19:00':'Chiuso'?></span></div><?php endforeach?></article><article class="panel setting"><h3>Configurazione agenda</h3><p>Definisci il comportamento del calendario.</p><label>Durata slot (minuti)<select><option>30 minuti</option><option>45 minuti</option></select></label><label>Giorni visibili in agenda<input type="number" value="7"></label><h3>Conti di saldo</h3><div class="account-chip">POS <button>×</button></div><div class="account-chip">Bonifico <button>×</button></div><div class="account-chip">Contanti <button>×</button></div><button class="primary">Salva modifiche</button></article></div>
<?php else: $c=$configs[$page]; ?>
<section class="toolbar"><div class="search"><?=icon('search')?><input placeholder="Cerca..."></div><button class="primary"<?=$page==='users'?' data-modal="user"':''?>><?=icon('plus')?> <?=$c[2]?></button></section><article class="panel table-panel"><div class="panel-head"><div><h3><?=$c[0]?></h3><p><?=$c[1]?></p></div><button class="secondary">Filtri</button></div><div class="table-scroll"><table><thead><tr><?php foreach($c[3] as $h):?><th><?=$h?></th><?php endforeach?><th></th></tr></thead><tbody<?=$page==='users'?' id="usersTableBody"':''?>><?php foreach($c[4] as $row):?><tr><?php foreach($row as $i=>$v):?><td><?=$i===0?'<b>'.$v.'</b>':$v?></td><?php endforeach?><td><button aria-label="Azioni">•••</button></td></tr><?php endforeach?></tbody></table></div></article>
<?php endif; ?>
